### ISSUE TITLE
Error from Slack: channel_not_found

### ISSUE THREAD

**Issue by asbjornu** [someimportantcompany/github-actions-slack-message#10]
It seems that providing `message-id` alongside `channel` causes the error `channel_not_found`, somehow. [This job shows the problem](https://github.com/SwedbankPay/search.developer.swedbankpay.com/runs/2746817262?check_suite_focus=true). The first step is executed successfully:

<img width="470" alt="Success" src="https://user-images.githubusercontent.com/12283/120819238-a9672a00-c553-11eb-8d8e-ee622c25acaa.png">

However, the later step that should update the message created in the first step, fails:

<img width="472" alt="Failure" src="https://user-images.githubusercontent.com/12283/120819316-bb48cd00-c553-11eb-996e-1bf4513c30eb.png">

**Comment by asbjornu** [comment]
I just tested now removing `channel` and that didn't work either:

<img width="450" alt="Error: Expected `channel` input since `bot-token` was passed" src="https://user-images.githubusercontent.com/12283/120822870-20ea8880-c557-11eb-8b9e-66d41efde2dc.png">

**Comment by jdrydn** [comment]
Hey @asbjornu, thanks for opening this.

`channel_not_found` comes from Slack's [`chat.update`](https://api.slack.com/methods/chat.update) API so I'm not entirely certain why you're getting this response when updating a message - especially when the create message request went through! 🤔 

One thing to note could be the `channel` you provide is the human-friendly name whereas the channel used in my CI workflow is the channel ID:

https://github.com/someimportantcompany/github-actions-slack-message/blob/2383926a06d942452f032802d3a270c730be2fdf/.github/workflows/test.yml#L9-L10

https://github.com/someimportantcompany/github-actions-slack-message/blob/2383926a06d942452f032802d3a270c730be2fdf/.github/workflows/test.yml#L31-L49

Could you replace your channel name with the ID & retest? See [`chat.postMessage` channels](https://api.slack.com/methods/chat.postMessage#channels) for information, but you can either grab the channel ID from [`conversations.list`](https://api.slack.com/methods/conversations.list) or from [the Slack web-app URL](https://app.slack.com/client):

> https:// app.slack.com /client/T0000000/ **G019R925BQA**

If this is successful, I likely need to update this action's documentation to explain the importance of channel ID, something which appears to be becoming more valued over those friendly `#channel` names Slack launched with!

**Comment by asbjornu** [comment]
Thanks for the swift reply! Yep, with channel ID it works. It may clarify things a bit if the YAML property was named `channel-id` and not just `channel`, perhaps.
