### ISSUE TITLE
node16 is deprecated

### ISSUE THREAD

**Issue by peterbe** [someimportantcompany/github-actions-slack-message#25]
Referring to this line: https://github.com/someimportantcompany/github-actions-slack-message/blob/969d01ed2e48e3a7d68b7c57004bfd1b6bbc6e85/action.yml#L7

It yields this warning every time it's used:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: someimportantcompany/github-actions-slack-message@1d367080235edfa53df415bd8e0bbab480f29bad. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jdrydn** [comment]
Thanks @peterbe - I'll release this now 👍

**Comment by peterbe** [comment]
> Thanks [@peterbe](https://github.com/peterbe) - I'll release this now 👍

Was this released? I only see v1 here: https://github.com/someimportantcompany/github-actions-slack-message/releases

**Comment by peterbe** [comment]
> Thanks [@peterbe](https://github.com/peterbe) - I'll release this now 👍

Kind ping reminder. 🏓

**Comment by jdrydn** [comment]
Hey @peterbe this was updated - and kept with the `@v1` tag as the action's inputs/outputs haven't changed!

<img width="1234" alt="image" src="https://github.com/someimportantcompany/github-actions-slack-message/assets/406967/fc66fcfb-f62a-4587-9985-f784a36cfe66">

Hopefully, you haven't seen the `node16` warning for this action anymore. I've also validated this myself with this test run [see this Test run](https://github.com/someimportantcompany/github-actions-slack-message/actions/runs/7986265076).

**Comment by peterbe** [comment]
Funnily enough, I noticed this minutes later. 
I think I had expected it to be a v1.1 release :)
All is working now.

**Comment by lamasfoker** [comment]
github action use the tag and not the release version. As of now if I want to use your github action with the latest node version i need to specify the version in this way
```
someimportantcompany/github-actions-slack-message@v1.5.0
```

Please tag the latest version v1.5.0 also as v1, as the others github action [mantainers](https://github.com/actions/cache/tags) do.

**Comment by alexdfaria** [comment]
I agree with @lamasfoker.

Or at least update the README to use the `someimportantcompany/github-actions-slack-message@v1.5.0` instead of the `@v1`.

**Comment by jdrydn** [comment]
Hey @lamasfoker & @alexdfaria - this has now been resolved ✌️

<img width="430" alt="image" src="https://github.com/user-attachments/assets/adec5405-cf86-4aa1-af08-95da0727c242">

**Comment by lamasfoker** [comment]
Thanks @jdrydn!
