### ISSUE TITLE
Customizable message title

### ISSUE THREAD

**Issue by asbjornu** [someimportantcompany/github-actions-slack-message#9]
It would be nice if the message title could be changed from `<job name> (#<sha>)` (typically `Test (#34da5705)`) to something different.

**Comment by jdrydn** [comment]
I like it - let's get some variable support in there too 👍

**Comment by jdrydn** [comment]
Done - added to v1.4.0 & published under v1, [see `title` option in the README](https://github.com/someimportantcompany/github-actions-slack-message#inputs).
